DROP TABLE IF EXISTS flappy_score_events CASCADE;
DROP TABLE IF EXISTS two048_move_events CASCADE;
DROP TABLE IF EXISTS tetris_snapshots CASCADE;
DROP TABLE IF EXISTS snake_food_events CASCADE;

DROP TABLE IF EXISTS game_sessions CASCADE;

DROP TYPE IF EXISTS game_type CASCADE;
DROP TYPE IF EXISTS direction CASCADE;
